# Site settings
title: "\\  jxkxl \\"
SEOTitle: ""
header-img: img/hollow-knight.png
email: cwand333@gmail.com
description: "Here you'll find my CTF write-ups and other random cyber stuff I am interested in"
keyword: "jxkxl, @jxkxl, jxkxl's Blog, CTF, Arch Linux"
url: "https://jxkx1.github.io" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
github_username: jxkx1
linkedin_username: andrew-currie-
tryhackme_username: jxkxl

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
# disqus_username: hynduf

# Netease settings
netease_comment: false

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "No technology that’s connected to the internet is unhackable."
sidebar-avatar: "/assets/pfp.jpeg" # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 0 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "3rd Place - BSides2024", href: "https://www.bsidesdub.ie/"},
    { title: "1st Place - ZeroDays2024", href: "https://www.setu.ie/news/setu-computing-students-win-at-all-ireland-of-cyber-security-competitions" },
    { title: "Team Ireland - ECSC2023", href: "https://cyberireland.ie/team-ireland-competes-in-the-european-cyber-security-challenge/" },
    { title: "Team Ireland - ECSC2022", href: "https://www.youtube.com/watch?v=LbueXz3He9Y"},
    { title: "2nd Place - ZeroDays2022", href: "https://www.setu.ie/news/setu-carlow-computing-students-place-2nd-in-the-ldquo-all-ireland-rdquo-of-cybersecurity-competitions"},
  ]
